Feature/t-step joint
gramaziokohler/compas_timber pull request #251
Opened 2024-05-06 13:24 UTC by jonashaldemann

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas_timber.datastructures.Beam`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

2024-05-06 13:29 UTC, jonashaldemann commented
@chenkasirer maybe there is some simplification potential in the code where I added a TODO comment...

2024-05-21 15:00 UTC, chenkasirer requested changes
Sorry I took so long. Looks nice! I made a first pass of comments. Let me know if there's anything that's not clear.

2024-05-22 11:56 UTC, jonashaldemann commented on src/compas_timber/connections/t_step.py
> +    # TODO simplify with Chen!
You are absolutely right. I have no idea how I came up with this :-/

2024-05-22 11:56 UTC, jonashaldemann commented on src/compas_timber/connections/t_step.py
> +        R = Rotation.from_axis_and_angle(rotation_axis, math.radians(90))
You are absolutely right. I have no idea how I came up with this :-/

2024-10-22 13:27 UTC, closed without merging

2024-10-22 13:28 UTC, jonashaldemann commented
currently being implemented by @papachap